### PR TITLE
topology: glk: fix channel count for dmic stereo recording

### PR DESCRIPTION
**Pull request by ranj063**
Fix the channel count to 2 for stereo dmic recording.

Signed-off-by: Ranjani Sridharan <ranjani.sridharan@linux.intel.com>

### CODE REVIEW

**Comment by ranj063** [comment]
@singalsu @lgirdwood I cant assign reviewers in the SOFT repo. But could you please help review this one?

**Comment by xiulipan** [comment]
@ranj063 Added reviewers for you.
Maybe you need to check if you get invitation for SOFT repo.

**Comment by lgirdwood** [comment]
@ranj063 you should have invite for soft. please check.

**Comment by ranj063** [comment]
@xiulipan @lgirdwood yes, sorry missed the invitation in my inbox. Thanks!

**Pull request merged**
