### PR TITLE
Fix glk virtual widget warnings

### PR DESCRIPTION
**Pull request by ranj063**

### CODE REVIEW

**Comment by ranj063** [comment]
Fixes https://github.com/thesofproject/soft/issues/135

**Comment by keqiaozhang** [comment]
Confirmed that this PR can fix #135.

**Comment by ranj063** [comment]
@keqiaozhang Thanks!

closing this one to re-open in SOF repo.

**Comment by cujomalainey** [comment]
@lgirdwood we should mark this repo as an archive to keep the data but prevent people from accidentally pushing to it

**Comment by mengdonglin** [comment]
@lgirdwood Will topology files also be moved to sof repo since this soft repo is deprecated?

**Comment by cujomalainey** [comment]
@mengdonglin yep, the whole repo was moved this past weekend

**Pull request closed without merging**
