### PR TITLE
soft: adding sof repo as a submodule

### PR DESCRIPTION
**Pull request by bkokoszx**
In order to avoid dependency between soft
and sof repository I've added sof repo as
a submodule. I've updated also logger files
to use includes from submodule

Signed-off-by: Bartosz Kokoszko <bartoszx.kokoszko@linux.intel.com>

### CODE REVIEW

**Comment by cujomalainey** [comment]
That seems counter intuitive. I spoke with @lgirdwood and I was going to put soft in sof this week and we're going to split the topology files out into another repo.

The nature of submodules is that these is a dependency between commits so I'm not sure how you are avoiding that.

**Comment by lgirdwood** [comment]
@bkokoszx yep as @cujomalainey says, although today is busy at ELCE.

**Comment by bkokoszx** [comment]
Ok, I understand. Thanks for your reply.

**Comment by cujomalainey** [comment]
@bkokoszx can you close this? I don't think we want to leave it open otherwise it might cause confusion

**Comment by bkokoszx** [comment]
@cujomalainey 
Hi, are there any updates in putting soft in sof?

**Comment by cujomalainey** [comment]
Unfortunately no, right now I am busy at work helping the other team integrate SOF into our kernel. Once that is finished I can come back to this

**Pull request closed without merging**
