### PR TITLE
logger: abi verification addition

### PR DESCRIPTION
**Pull request by bkokoszx**
I've added abi_version verification. Be default we verify: abi in *.ldc file with logger abi version.
We additionally can verify abi in "/sys/kernel/debug/sof/fw_version" (with -e flag) or in ver_file (with -v ver_file) with logger abi version.

### CODE REVIEW

**Comment by bkokoszx** [comment]
@lgirdwood
btw why are in SOF_ABI_VERSION_INCOMPATIBLE macro we only comparing MAJOR version?

**Comment by lgirdwood** [comment]
@bkokoszx please see Semantic versioning, the MINOR and PATCH updates are not meant to break ABI (so user will still work albeit with out the new feature or fix).

**Review by lgirdwood — CHANGES_REQUESTED** [review]
I think the easiest change is just to move to sof.git repo, as I guess @cujomalainey has limited free time atm  ? so please feel free to create a tools directory in sof.git (with rimage and logger in this subdir). I dont need to keep logger history.

**Comment by bkokoszx** [comment]
@lgirdwood 
I've a little question.
Should it be one option for making all tools like:
./configure --enable-tools (it will build either logger and rimage)
or should I make a separation between them split into rimage and logger part like:
./configure --enable-rimage 
./configure --enable-logger ?
Thanks

**Comment by lgirdwood** [comment]
@bkokoszx best to make them all go under tools (keeps things simple too)

**Comment by bkokoszx** [comment]
@lgirdwood 
I've made this under following PR:
https://github.com/thesofproject/sof/pull/618

**Comment by bkokoszx** [comment]
@lgirdwood 
Maybe it will be a good idea to merge above PR before @cujomalainey relocation path?

These changes are also incorporated in: https://github.com/thesofproject/sof/pull/618.

**Comment by lgirdwood** [comment]
@bkokoszx I was thinking that, but since this PR has copies of the ABI headers it will duplicate them in SOF. Probably best to sort this after @cujomalainey PR merge. Them we can include the local ABI headers directly.

**Comment by cujomalainey** [comment]
I'm guessing we solve this by correcting the includes to the literal locations? The only option i can think of would be a symlink and that just seems confusing to developers.

**Comment by bkokoszx** [comment]
Yes, I think we should solve it by changing to literal locations. 
@lgirdwood 
I will make this patch (abi verification) again and directly to SOF repo, after merging:
https://github.com/thesofproject/sof/pull/624

**Pull request closed without merging**
