### PR TITLE
[RFC] Changes to SectionPCM macros

### PR DESCRIPTION
**Pull request by ranj063**
This pull request proposes to make the following changes the macro definitions for the SectionPCM. 

1. remove pipeline_id: this is not used in the kernel and a pcm_id could be associated with multiple pipelines
2. make dai_id optional: CPU DAI ID for FE DAI links should be assigned by the core based on the 
component->num_dai which is incremement every time a new DAI link is added. So make it optional in case, there arises a need to assign a specific ID in future.

### CODE REVIEW

**Comment by ranj063** [comment]
@xiulipan @plbossart could you please help review this ?
Only tested to work on the Up squared board.

**Comment by ranj063** [comment]
@plbossart I left it as optional because the core still looks for the dai_id from the topology and only assigns num_dai when it is omitted in topology.

**Comment by ranj063** [comment]
@plbossart I agree there is no use for this in SOF today. I can update the PR to remove this if @lgirdwood and @xiulipan are OK with it too.

**Comment by lgirdwood** [comment]
@ranj063 please update then we can merge after 1.2

**Comment by ranj063** [comment]
@lgirdwood @plbossart I've removed dai_id too. 
I'm working with the team to get it tested on all platforms. I will notify after the tests pass.

**Comment by ranj063** [comment]
@plbossart I've updated this pull request to add the dai_name back to SectionPCM.

**Comment by plbossart** [comment]
This update doesn't work at all for me on Reef. I get no sound on hw:0,0 (only a loud pop then nothing) and reboot everytime hw:0,1 is used. there is something really fishy about all this with a likely confusion between ids again.

**Comment by ranj063** [comment]
@plbossart agree this pull request needs some more testing. But I havent seen the issue in up squared whn using hw:0,1

**Comment by plbossart** [comment]
When I apply this patch and change my sof-apl-da7219.m4 file I see 
changes in the conf file that don't look right

diff --git a/topology/sof-apl-da7219.m4 b/topology/sof-apl-da7219.m4
index eea3ce3..72144fc 100644
--- a/topology/sof-apl-da7219.m4
+++ b/topology/sof-apl-da7219.m4
@@ -76,8 +76,8 @@ DAI_ADD(sof/pipe-dai-playback.m4,
  # this was used on for sof-apl-pcm512x, no idea why there are two 
pipelines
  # PCM_PLAYBACK_ADD(Port5, 0, 0, 0, PIPELINE_PCM_1, PIPELINE_PCM_2)

-PCM_PLAYBACK_ADD(SSP5, 0, 0, 0, PIPELINE_PCM_1)
-PCM_PLAYBACK_ADD(SSP1, 1, 1, 1, PIPELINE_PCM_2)
+PCM_PLAYBACK_ADD(SSP5, 0, PIPELINE_PCM_1)
+PCM_PLAYBACK_ADD(SSP1, 1, PIPELINE_PCM_2)
  #PCM_CAPTURE_ADD(dmic01, 2, 2, 2, PIPELINE_PCM_3)

  #


diff sof-apl-da7219.conf old.conf915a916,917
 >     index "0"
 >
919a922
 >         id "0"
928a932,933
 >     index "1"
 >
932a938
 >         id "1"

The replacement looks very suspicious.

**Pull request merged**
